### ISSUE TITLE
🐛 BUG: Sitemap 0.20 introduces `ERR_MODULE_NOT_FOUND`

### ISSUE THREAD

**Issue by tusamni** [withastro/astro#3660]
### What version of `astro` are you using?

1.0.0-beta.48

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

NPM

### What operating system are you using?

Windows 11

### Describe the Bug

When running `npm run build` with the sitemap package it'll throw the following error:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\erik\Downloads\sites\astro-blog-portfolio\node_modules\@astrojs\sitemap\dist\generate-sitemap' imported from C:\Users\erik\Downloads\sites\astro-blog-portfolio\node_modules\@astrojs\sitemap\dist\index.js`

This happens on a manual install as well as the Astro Add CLI command.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-de1e1j?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by felixsanz** [comment]
Note: This seems to be working fine with sitemap 0.1.2 and Astro b.44 (the previous version)
