### ISSUE TITLE
Vercel adapter:  error   this[kFormat] is not a function

### ISSUE THREAD

**Issue by tefkah** [withastro/astro#5090]
### What version of `astro` are you using?

1.4.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn, pnpm

### What operating system are you using?

Mac, Linux

### Node version

`v16.17.0`

### Describe the Bug

When trying to `build` or `dev` Astro with the vercel adapter, Astro creates the following error. It seems to work on `1.5.0` though!

When using `output: "static"` everything works fine. It also used to work with the Netlify adapter, although that one yields a different error.

```sh
 error   this[kFormat] is not a function
  Code:
      58 |         await removeDir(buildTempFolder);
    > 59 |         await writeJson(new URL(`./package.json`, functionFolder), {
         |                          ^
      60 |           type: "module"
      61 |         });
      62 |         await writeJson(new URL(`./.vc-config.json`, functionFolder), {
    
  Stacktrace:
TypeError: this[kFormat] is not a function
    at Object.toString (node:internal/url:744:25)
    at new URL (node:internal/url:634:5)
    at new URL (node:internal/url:637:22)
    at Object.astro:config:done (/Volumes/SSD/Projects/astro-fail/node_modules/.pnpm/@astrojs+vercel@2.2.0/node_modules/@astrojs/vercel/dist/serverless/adapter.js:59:26)
    at runHookConfigDone (file:///Volumes/SSD/Projects/astro-fail/node_modules/.pnpm/astro@1.4.7/node_modules/astro/dist/integrations/index.js:81:59)
    at dev (file:///Volumes/SSD/Projects/astro-fail/node_modules/.pnpm/astro@1.4.7/node_modules/astro/dist/core/dev/index.js:36:9)
    at async startDevServer (file:///Volumes/SSD/Projects/astro-fail/node_modules/.pnpm/astro@1.4.7/node_modules/astro/dist/cli/index.js:144:35)
    at async runCommand (file:///Volumes/SSD/Projects/astro-fail/node_modules/.pnpm/astro@1.4.7/node_modules/astro/dist/cli/index.js:185:7)
    at async cli (file:///Volumes/SSD/Projects/astro-fail/node_modules/.pnpm/astro@1.4.7/node_modules/astro/dist/cli/index.js:207:5)
```

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/floral-frog-12n7g2?file=%2F.codesandbox%2Ftasks.json&selection=%5B%7B%22endColumn%22%3A42%2C%22endLineNumber%22%3A25%2C%22startColumn%22%3A42%2C%22startLineNumber%22%3A25%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8vqm7910009lthi9ed6fwlg%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fastro.config.ts%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252Fpages%252Findex.astro%2522%252C%2522%252Fsrc%252Fenv.d.ts%2522%252C%2522%252Ftsconfig.json%2522%252C%2522%252F.npmrc%2522%252C%2522%252F.codesandbox%252Ftasks.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl984rihy002tlqcr99852ajl%2522%252C%2522key%2522%253A%2522cl984rif600pt3b6h39buth53%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl95ry4ax000dlqcreugmecqa%2522%252C%2522key%2522%253A%2522cl95ry47z00a53b6h5d385i4w%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl984s0u400tu3b6hsopwf5m9%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl95rxvyd006z3b6h6c8p6bp6%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tefkah** [comment]
Sorry, this is fixed in 1.5.0!
