### ISSUE TITLE
Astro build fails with Content Collection glob loader on Apple Silicon Docker due to Sätteri native binding resolution

### ISSUE THREAD

**Issue by i-daisuke** [withastro/astro#17153]
### Astro Info

```block
Astro                    v7.0.0
Vite                     v8.0.16
Node                     v26.3.1
System                   Linux (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react (v6.0.0)
```

### Describe the Bug

After upgrading Astro from v6 to v7, `npm run dev` starts successfully in my environment, but `npm run build` fails inside a Docker container running on Apple Silicon.

The failure happens during content sync with a Sätteri native binding error.

The issue is reproducible when using a Content Collection with the `glob` loader and rendering Markdown content.

Sätteri tries to load `@bruits/satteri-linux-arm64-gnu`, but this package does not appear to exist in `satteri`'s optional dependencies.

The issue is avoided by forcing Docker to use `linux/amd64`.

#### Error

```txt
Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
  Stack trace:
    at file:///app/node_modules/satteri/index.js:575:11
    at async node:internal/modules/esm/loader:646:26
    at async createSatteriMarkdownProcessor (file:///app/node_modules/@astrojs/markdown-satteri/dist/satteri-processor.js:182:13)
    at async syncData (/app/node_modules/astro/dist/content/loaders/glob.js:118:16)
  Caused by:
  Cannot find module '@bruits/satteri-linux-arm64-gnu'
Require stack:
- /app/node_modules/satteri/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1519:15)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1097:10)
    at nextStep (node:internal/modules/customization_hooks:189:26)
    at nextStep (node:internal/modules/customization_hooks:189:26)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1167:25)
```

#### Environment

* Host machine: Mac with Apple Silicon, M4
* Docker image: `node:26-trixie-slim`
* Container architecture without workaround: `linux arm64`
* Astro version: `v7.0.0`
* Node version: `v26.3.1`

#### Steps to reproduce

1. Use a Mac with Apple Silicon.
2. Run the minimal reproduction in Docker using `node:26-trixie-slim`.
3. Install dependencies.
4. Run:

```sh
npm run build
```

5. The build fails during content sync with the Sätteri native binding error.

#### Additional notes

I checked `node_modules/satteri/package.json`, and the optional dependencies were:

```json
"optionalDependencies": {
  "@bruits/satteri-linux-x64-gnu": "0.9.1",
  "@bruits/satteri-darwin-x64": "0.9.1",
  "@bruits/satteri-darwin-arm64": "0.9.1",
  "@bruits/satteri-win32-x64-msvc": "0.9.1",
  "@bruits/satteri-wasm32-wasi": "0.9.1"
}
```

There is no `@bruits/satteri-linux-arm64-gnu` package listed.

The issue is avoided by forcing Docker to use `linux/amd64`:

```yaml
services:
  app:
    platform: linux/amd64
```

After this, the installed native package is:

```txt
@bruits/satteri-linux-x64-gnu
```

and `npm run build` succeeds.

### What's the expected result?

`npm run build` should complete successfully in an Apple Silicon Docker environment running Linux arm64.

If Linux arm64 is not currently supported by Sätteri, Astro should show a clearer error message explaining the unsupported environment or fallback behavior instead of trying to load a non-existent native package.

### Link to Minimal Reproducible Example

https://github.com/i-daisuke/astro-satteri-arm64-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jakst** [comment]
@astrobot-houston it is not a docker-only issue. It also affects any machine running ARM64 without docker, like a CI machine. In those cases it's harder to work around.

**Comment by matthewp** [comment]
@jakst Thanks for the report, will have fixed soon.

**Comment by Princesseuh** [comment]
Sätteri's latest update `0.9.2` has optionalDeps for this target and more: https://npmx.dev/package/@bruits/satteri-linux-arm64-gnu

**Comment by i-daisuke** [comment]
I confirmed that the issue is resolved with satteri@0.9.2.

After removing the platform: linux/amd64 workaround and reinstalling dependencies, npm run build completed successfully in the linux/arm64 Docker environment.

Thank you!
