### ISSUE TITLE
"astro/loaders" import gives not available warning in VScode

### ISSUE THREAD

**Issue by xkeshav** [withastro/astro#12841]
### Astro Info

```block
astro info
Astro                    v5.1.1
Node                     v22.0.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  @astrojs/node
Integrations             astro-icon
                         @astrojs/tailwind
                         @astrojs/react
                         @astrojs/tailwind
                         astro-i18next
```

### If this issue only occurs in one browser, which browser is a problem?

in VS Code

### Describe the Bug

using new `defienCollection` method  and taking refrence from (the official docs)[https://docs.astro.build/en/guides/content-collections/] and in the code spinnets  it says

`import { glob, file } from 'astro/loaders'; // Not available with legacy API`

what this means? I have upgraded to astro 5.1.1 and related packages too  

I am able to use it but it gives error in VS Code above the import statment

>Cannot find module 'astro/loaders' or its corresponding type declarations.
 > There are types at '/home/project/name/node_modules/astro/dist/content/loaders/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

### What's the expected result?

 'astro/loaders' should not gives error in VS code

### Link to Minimal Reproducible Example

![image](https://github.com/user-attachments/assets/b56c9331-5161-4ec6-8419-092483ff81bf)
### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
You're defining an old content collection in a file that accepts only new content collections.

`articles` is an old content collection because it doesn't have a `loader`, and `content.config.ts` accepts only content collections that have loaders.

**Comment by xkeshav** [comment]
i have set the loades but it says to change in tsconfig settings and if I change `"moduleResolution"` value  to `"nodenext"` , it gives error on other pages

 > but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)

**Comment by rodilo** [comment]
@xkeshav did you find solution for this? I'm facing the same issue now when i upgraded astro to 5.3.

**Comment by xkeshav** [comment]
As I remember, but not sure, it was resolved by doing a fresh npm install  and reload window

**Comment by rodilo** [comment]
> As I remember, but not sure, it was resolved by doing a fresh npm install and reload window

I managed to resolve it by setting `moduleResolution` to `bundler`.
