### ISSUE TITLE
astro/rss: type of rssSchema changed so it can no longer be extended

### ISSUE THREAD

**Issue by wkillerud** [withastro/astro#9744]
### Astro Info

```block
Astro                    v4.2.1
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### Describe the Bug

Hello 👋 

#9610 introduced a [change to `rssSchema`](https://github.com/withastro/astro/pull/9610/files#diff-01273eb750ee014202811acc2c006387a1f903dd4d33ea6994f0d2748ceed582) where it went from being a Zod object to being a Zod union.

I don't remember where I picked up this pattern, but my goal is to ensure I have a collection that conforms to the RSS spec. At the same time I have some custom fields in the frontmatter that I use in my blog post template `.astro`.

This collection works with `@astro/rss@4.0.1`. In `@astro/rss@4.0.2` it causes an error: `__vite_ssr_import_1__.rssSchema.extend is not a function`

```js
import { z, defineCollection } from "astro:content";
import { rssSchema } from "@astrojs/rss";

const blogCollection = defineCollection({
	schema: ({ image }) =>
		rssSchema.extend({
			category: z.string().optional(),
			cover: z
				.object({
					image: image(),
					alt: z.string(),
				})
				.optional(),
		}),
});

export const collections = {
	blog: blogCollection,
};
```

### What's the expected result?

My expectation when upgrading was for `rssSchema.extend` to continue to work, but I'll freely admit I might just be doing something silly here 🙈 

Should I add the other fields some different way?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yuurwk?file=src%2Fcontent%2Fconfig.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
You're right, extend cannot be used on an union. I even had to rework things to avoid using it! I'll submit a PR to use a simple object instead

**Comment by wkillerud** [comment]
`@astro/rss@4.0.3` still throws an error when trying to call `.extend`. I opened a PR with a suggested fix in #9797
