### ISSUE TITLE
Astro doesn't aware about svelte props

### ISSUE THREAD

**Issue by Leniorko** [withastro/astro#14681]
### What version of `astro` are you using?

2.8.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I add svelte into my new project with `pnpm astro add svelte`

After writing some component with svelte using TS, I have a couple of typed props like `position` and `whereTo`:
```svelte
<script lang="ts">
  import Home from "svelte-material-icons/Home.svelte"; 

  export let position:
    | "top-left"
    | "top-right"
    | "bottom-left"
    | "bottom-right" = "bottom-right";

  export let whereTo: string = "#";

  const positionClass = `FAB-${position}`;
</script>
```

 I'm adding this component directly to Astro page. But Astro doesn't seem to be aware about defined props because when I'm hovering over a component in `.astro` file typing looks like this:

```ts
(alias) function FAB(_props: any): any
import FAB
```

Types when importing svelte component into another svelte component works perfectly fine. Type when hovering over looks like this:

```ts
(alias) class FAB
import FAB
```

### What's the expected result?

Proper types in `.astro` file. Or at least the opportunity to define them manually. I'm sorry if there is one, but I can't find information about it.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-njqqdd?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kwshi** [comment]
On a somewhat related note: with `shamefully-hoist` disabled (the new default setting), Svelte isn't the only thing that breaks-- trying to open any astro file and thereby launch the astro language server fails with the following error:

```
Cannot find typescript.js or tsserverlibrary.js in (path-to-project)/node_modules/typescript/lib
```

![image](https://github.com/withastro/astro/assets/3887189/679d8c75-47aa-4c8b-8efa-adb24d7b0ec7)


unless typescript is explicitly installed as a project-level dependency. Weirdly, the astro language server insists on loading typescript _only_ from the project-level `node_modules/`, and not from, e.g., the global paths. This is an issue that only Astro seems to have (other language servers I have installed, e.g., svelte, do not have this issue), and it is also "fixed" by `shamefully-hoist=true`.

**Comment by kylemclean** [comment]
This is still not working with Astro 5.9.2 and Svelte 5.34.1.

I am also using npm 10.9.2.

**Comment by anmoti** [comment]
It still doesn't work in Astro 5.13.4.
I tried using pnpm, adding `shamefully-hoist=true` and `public-hoist-pattern[]=svelte2tsx` to `.npmrc`, and reinstalling node_modules, but it didn't change anything.

I think it worked up to Svelte 4, but it seems to have stopped working after Astro upgraded to 5.
Probably just my memory playing tricks on me, so please don't worry about it.
