### ISSUE TITLE
NPM cannot resolve Astro Actions virtual module

### ISSUE THREAD

**Issue by haetae-bit** [withastro/astro#14572]
### Astro Info

```block
I'm working on a WSL2 setup, but here's the info I got from `astro info`:

Astro                    v5.14.6
Vite                     v6.4.0
Node                     v22.20.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node (v9.5.0)
```

### Describe the Bug

I've been developing my project with Astro using `pnpm`, but when I try running my project with `npm`, I get this error when I start my development server using `npm run dev`:

```bash
✘ [ERROR] Could not resolve "virtual:astro:actions/options"

    node_modules/astro/dist/virtual-modules/actions.js:1:42:
      1 │ import { shouldAppendTrailingSlash } from "virtual:astro:actions/options";
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:astro:actions/options" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "virtual:astro:actions/runtime"

    node_modules/astro/dist/virtual-modules/actions.js:10:14:
      10 │ export * from "virtual:astro:actions/runtime";
         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:astro:actions/runtime" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

18:52:47 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
Error: Build failed with 2 errors:
node_modules/astro/dist/virtual-modules/actions.js:1:42: ERROR: Could not resolve "virtual:astro:actions/options"
node_modules/astro/dist/virtual-modules/actions.js:10:14: ERROR: Could not resolve "virtual:astro:actions/runtime"
```

I can't find any way where this unhandled rejection might be coming from and prevents a dev server from running at all.

### What's the expected result?

I would expect a more precise message of _where_ this unhandled error would be instead of throwing an error immediately on a virtual import.

I'll link to the project this issue is happening at the moment since producing a minimal reproduction didn't seem to throw the same error.

### Link to Minimal Reproducible Example

https://github.com/haetae-bit/fanfic-atproto

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by haetae-bit** [comment]
Update: It turns out that one of my Preact components was preventing the dev server to run because I was using an Astro Action in there. Is there documentation on UI frameworks being able to use Astro Actions or am I being dumb?

**Comment by florian-lefebvre** [comment]
Looks like I introduced a regression in #14538. In the meantime you can downgrade to 5.14.5

**Comment by florian-lefebvre** [comment]
I cannot reproduce with your repo. Here's what I've done:

- Clone
- Run `npm i`
- Run `npm run dev`
- Go to `/`, `/works`, `/works/1235`

I never got the warning. I also tried with `pnpm`. Can you give me more precise steps?

**Comment by whallin** [comment]
Experiencing the same error as OP:

```bash
09:46:13 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
Error: Build failed with 2 errors:
node_modules/astro/dist/virtual-modules/actions.js:1:42: ERROR: Could not resolve "virtual:astro:actions/options"
node_modules/astro/dist/virtual-modules/actions.js:10:14: ERROR: Could not resolve "virtual:astro:actions/runtime"
    at failureErrorWithLog (F:\GitHub\newgentdigital\website\node_modules\vite\node_modules\esbuild\lib\main.js:1467:15)
    at F:\GitHub\newgentdigital\website\node_modules\vite\node_modules\esbuild\lib\main.js:926:25
    at F:\GitHub\newgentdigital\website\node_modules\vite\node_modules\esbuild\lib\main.js:1345:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  Hint:
    Make sure your promises all have an `await` or a `.catch()` handler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unhandled-rejection/
  Stack trace:
    at F:\GitHub\newgentdigital\website\node_modules\astro\dist\virtual-modules\actions.js: ERROR: Could not resolve "virtual:astro:actions\options":1:42
    [...] See full stack trace in the browser, or rerun with --verbose
```

As suggested by @florian-lefebvre - downgrading to 5.14.5 solves this issue. Building the project works fine, development mode does not.

For (a not so minimal) reproduction, clone https://github.com/newgentdigital/website and run `bun dev` or `astro dev` as is.

My `astro info` output:

```
Astro                    v5.14.6
Node                     v22.20.0
System                   Windows (x64)
Package Manager          bun
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
                         @astrojs/mdx
                         @sentry/astro
                         @astrojs/react
```

**Comment by florian-lefebvre** [comment]
I can reproduce with `pnpm i && pnpm dedupe && pnpm astro dev`, thanks!

**Comment by florian-lefebvre** [comment]
Can you help me by trying out this preview release? Thank you

https://github.com/withastro/astro/pull/14582#issuecomment-3421692161

**Comment by mark-mybaggage** [comment]
@florian-lefebvre the [preview release](https://github.com/withastro/astro/pull/14582#issuecomment-3421692161) resolved the issue for me
