### ISSUE TITLE
server:defer with "getRelativeLocaleUrl" crashes with "undefined is not a function" on "virtual:astro:routes"

### ISSUE THREAD

**Issue by talensjr** [withastro/astro#17785]
### Astro Info

```block
Astro                    v7.2.4
Vite                     v8.2.2
Node                     v22.22.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/node (v11.1.4)
Integrations             none
```

### Describe the Bug

Using `server:defer` on a minimal Astro component causes the dev server to fail when another component in the same page imports `getRelativeLocaleUrl` from `astro:i18n`.

It does work fine on version `7.2.2` of Astro, it does not work from `7.2.3` upwards.

Error: 

```
undefined is not a function (The stacktrace appears to be already rewritten by something else, but was passed to vite.ssrFixStacktrace. This may cause incorrect stacktraces.)

```

Stack trace:

```
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at eval (virtual:astro:routes:9:35)
    at async ESModulesEvaluator.runInlinedModule (file:///home/projects/withastro-astro-ggchumjw/node_modules/vite/dist/node/module-runner.js:1046:3)
    at async ModuleRunner.directRequest (file:///home/projects/withastro-astro-ggchumjw/node_modules/vite/dist/node/module-runner.js:1298:59)
    at async ModuleRunner.cachedRequest (file:///home/projects/withastro-astro-ggchumjw/node_modules/vite/dist/node/module-runner.js:1205:73)
    at async eval (virtual:astro:manifest:7:31)
    at async ESModulesEvaluator.runInlinedModule (file:///home/projects/withastro-astro-ggchumjw/node_modules/vite/dist/node/module-runner.js:1046:3)
    at async ModuleRunner.directRequest (file:///home/projects/withastro-astro-ggchumjw/node_modules/vite/dist/node/module-runner.js:1298:59)
    at async ModuleRunner.cachedRequest (file:///home/projects/withastro-astro-ggchumjw/node_modules/vite/dist/node/module-runner.js:1205:73)
    at async eval (/home/projects/withastro-astro-ggchumjw/node_modules/astro/dist/core/manifest/ambient.js:9:31)
```

### What's the expected result?

`server:defer` should defer only the marked component. The page should start successfully, and the static shell should load the deferred component through its generated server-island endpoint.

The following should work without requiring a custom Vite workaround:

```text
GET /
GET /_server-islands/Example?...
```

The `astro:i18n` import should remain valid and should not cause `virtual:astro:routes` route deserialization to fail.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ggchumjw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by talensjr** [comment]
I have tested it on my minimal local reproduction project (very similar to the link provided on StackBlitz) and it worked with no issues!! Looks like it is fixed, thanks for being so quick 😄
